[tool.poetry]
name = "tap-auth0"
version = "0.3.1"
description = "`tap-auth0` is a Singer tap for Auth0, built with the Meltano SDK for Singer Taps."
authors = ["Reuben Frankel", "Daniel Walker"]
keywords = [
    "ELT",
    "Auth0",
]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "<3.11,>=3.7.1"
requests = "^2.25.1"
singer-sdk = "^0.14.0"
ndjson = "^0.3.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^3.24.4"
flake8 = "^4.0.1"
black = "^22.3.0"
pydocstyle = "^6.1.1"
mypy = "^0.910"
types-requests = "^2.26.1"
isort = {extras = ["colors"], version = "^5.10.1"}
responses = "0.17.0"
pre-commit = "^2.17.0"
autoflake = "^1.4"

[tool.black]
include = "tap_auth0"
extend-exclude = "tests"
color = "true"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_auth0"
extend_skip = "tests"
color_output = "true"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-auth0 = 'tap_auth0.tap:TapAuth0.cli'
